### ISSUE TITLE
Dictionary complications with sample code in README

### ISSUE THREAD

**Issue by whogben** [stanjosh/oauth2-godot#1]
In the readme the sample code is:
```gdscript
var oauth_credentials = {
	oauth2_port:54140,
	oauth2_binding:"127.0.0.1",
	oauth2_client_id:"example",
	oauth2_client_secret:"example",
	oauth2_auth_server:"URI",
	oauth2_token_req:"URI",
	oauth2_token_key:"password"
}
```
Which crashes in current Godot (```oauth2_port not declared in current scope```)
To get it working I changed the dictionary keys to strings, and removed the "2" from the keys, eg:
```gdscript
var oauth_credentials = {
	'oauth_port':54140,
	'oauth_binding':"127.0.0.1",
	'oauth_client_id':"xxx.apps.googleusercontent.com",
	'oauth_client_secret':"xxx",
	'oauth_auth_server':"https://accounts.google.com/o/oauth2/v2/auth",
	'oauth_token_req':"https://oauth2.googleapis.com/token",
	'oauth_token_key':"password"
}
```

**Comment by stanjosh** [comment]
Glad you edited that 😉I will take a look

**Comment by whogben** [comment]
Haha yes, pretty silly of me to post my client_id and client_secret the first time! Thankfully they were test keys and only my user is authorized :p I'll go slower next time

**Comment by stanjosh** [comment]
I updated the readme. I had error checking in there but only if the keys were right in the dictionary. It was a matter of the readme version saying oauth2_ and the code saying oauth_

And, of course, the quotation marks. Try it now!

**Comment by stanjosh** [comment]
Ah, I see that you found the solution now. I will resubmit to the assetlib i suppose
