### ISSUE TITLE
OAuth flow looks normal on browser, but user_info is {} and a warning is generated: `refresh_tokens(): invalid_request : Missing required parameter: refresh_token`

### ISSUE THREAD

**Issue by whogben** [stanjosh/oauth2-godot#2]
When I run this sample code it generates a warning right before it opens the browser for OAuth.

The OAuth flow in the browser looks good (get the google page then the close and return to tab page).

The code then prints out "{}" to the console.

```gdscript
extends Node

func _ready():
	
	var oauth_credentials = {
		'oauth_port':54140,
		'oauth_binding':"127.0.0.1",
		'oauth_client_id':"xxx.apps.googleusercontent.com",
		'oauth_client_secret':"xxx",
		'oauth_auth_server':"https://accounts.google.com/o/oauth2/v2/auth",
		'oauth_token_req':"https://oauth2.googleapis.com/token",
		'oauth_token_key':""
	}
	
	var oauth = Oauth2.new(oauth_credentials)
	add_child(oauth)

	await oauth.authorize()
	print(oauth.user_info)
```

```
W 0:00:12:0224   oauth.gd:112 @ refresh_tokens(): invalid_request : Missing required parameter: refresh_token
  <C++ Source>   core/variant/variant_utility.cpp:1112 @ push_warning()
  <Stack Trace>  oauth.gd:112 @ refresh_tokens()
                 oauth.gd:188 @ _http_post()
```

**Comment by stanjosh** [comment]
The warning is part of the process, but I suppose you don't really need to see it lol. I'll take it out.

And you're saying that the user info isn't there, after authorizing?

**Comment by stanjosh** [comment]
I guess I neglected to point out that it's all signal driven and you can't await the results. I will document this in the readme

**Comment by stanjosh** [comment]
In the meantime, there's an example button script which shows the usage of the signals

**Comment by whogben** [comment]
perfecto! Adding `await oauth.token_authorized` made it work perfectly - great addon thank you!
